
version: '3.8'

services:
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: healthcare_platform_development
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/healthcare_platform_development
      RAILS_ENV: development
      RAILS_MASTER_KEY: supersecretkey123
      SECRET_KEY_BASE: supersecretkey123supersecretkey123supersecretkey123supersecretkey123
      JWT_SECRET_KEY: supersecretkey123
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/rails
    user: root
    entrypoint: ["/rails/entrypoint.sh"]
    command: bash -c "cd /rails && bundle install && bundle exec rails db:create db:migrate && bundle exec rails server -b 0.0.0.0"

  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: http://backend:3000
    ports:
      - "3001:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev

volumes:
  postgres_data:
